/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpinnerDateModel;
import javax.swing.filechooser.FileSystemView;
import model.ResultType;

/**
 *
 * @author megan
 */
public class MainWindow extends javax.swing.JFrame {

    
    private GUI_State gui_state;
    private SpinnerDateModel first_panel_date_time_model;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
                
        initComponents();
        
        gui_state = new GUI_State();
        first_panel_date_time_model = (SpinnerDateModel) first_panel_date_time.getModel();
        first_panel_date_time.setModel(first_panel_date_time_model);

        
        Date date = first_panel_date_time_model.getDate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        first_panel_title = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        first_panel_date_time = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        first_panel_button_loadFile = new javax.swing.JButton();
        first_panel_text_field_path = new javax.swing.JTextField();
        first_panel_protect_checkBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        first_panel_compress_checkBox = new javax.swing.JCheckBox();
        first_panel_module_size_comboBox = new javax.swing.JComboBox<>();
        first_panel_insert_error_checkBox = new javax.swing.JCheckBox();
        first_panel_button_accept = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        second_panel_title_label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        second_panel_text_field_path = new javax.swing.JTextField();
        second_panel_file_button = new javax.swing.JButton();
        second_panel_unprotect_checkBox = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        second_panel_fix_checkBox = new javax.swing.JCheckBox();
        second_panel_unzip_checkBox = new javax.swing.JCheckBox();
        second_panel_button_accept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Hamming - Huffman");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        first_panel_title.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        first_panel_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        first_panel_title.setText("Proteger - Compactar");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fecha de descompactación:");

        first_panel_date_time.setModel(new SpinnerDateModel(new Date(), new Date(), null, java.util.Calendar.MINUTE));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Archivo:");

        first_panel_button_loadFile.setText("Examinar");
        first_panel_button_loadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_panel_button_loadFileActionPerformed(evt);
            }
        });

        first_panel_text_field_path.setEditable(false);

        first_panel_protect_checkBox.setText("Proteger");
        first_panel_protect_checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_panel_protect_checkBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Tamaño del módulo:");

        jLabel6.setText("Insertar error:");

        first_panel_compress_checkBox.setText("Compactar");
        first_panel_compress_checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_panel_compress_checkBoxActionPerformed(evt);
            }
        });

        first_panel_module_size_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "32", "128", "1024", "4096", "16384" }));
        first_panel_module_size_comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_panel_module_size_comboBoxActionPerformed(evt);
            }
        });

        first_panel_insert_error_checkBox.setText("Si");
        first_panel_insert_error_checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_panel_insert_error_checkBoxActionPerformed(evt);
            }
        });

        first_panel_button_accept.setText("Aceptar");
        first_panel_button_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_panel_button_acceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(first_panel_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(first_panel_button_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(first_panel_date_time, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(first_panel_text_field_path)
                                .addGap(18, 18, 18)
                                .addComponent(first_panel_button_loadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(first_panel_insert_error_checkBox)
                            .addComponent(first_panel_module_size_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(first_panel_compress_checkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(first_panel_protect_checkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(first_panel_title)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(first_panel_date_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(first_panel_text_field_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first_panel_button_loadFile))
                .addGap(18, 18, 18)
                .addComponent(first_panel_protect_checkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(first_panel_module_size_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(first_panel_insert_error_checkBox))
                .addGap(18, 18, 18)
                .addComponent(first_panel_compress_checkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(first_panel_button_accept)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        second_panel_title_label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        second_panel_title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        second_panel_title_label.setText("Desproteger - Descompactar");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Archivo:");

        second_panel_text_field_path.setEditable(false);

        second_panel_file_button.setText("Examinar");
        second_panel_file_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                second_panel_file_buttonActionPerformed(evt);
            }
        });

        second_panel_unprotect_checkBox.setText("Desproteger");
        second_panel_unprotect_checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                second_panel_unprotect_checkBoxActionPerformed(evt);
            }
        });

        jLabel9.setText("Corregir error:");

        second_panel_fix_checkBox.setText("Si");
        second_panel_fix_checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                second_panel_fix_checkBoxActionPerformed(evt);
            }
        });

        second_panel_unzip_checkBox.setText("Descompactar");
        second_panel_unzip_checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                second_panel_unzip_checkBoxActionPerformed(evt);
            }
        });

        second_panel_button_accept.setText("Aceptar");
        second_panel_button_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                second_panel_button_acceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(second_panel_title_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(second_panel_button_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(second_panel_text_field_path, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(second_panel_file_button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(second_panel_unprotect_checkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(second_panel_unzip_checkBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel9)))
                        .addGap(52, 52, 52)
                        .addComponent(second_panel_fix_checkBox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(second_panel_title_label)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(second_panel_text_field_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(second_panel_file_button))
                .addGap(18, 18, 18)
                .addComponent(second_panel_unprotect_checkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(second_panel_fix_checkBox))
                .addGap(18, 18, 18)
                .addComponent(second_panel_unzip_checkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(second_panel_button_accept)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void first_panel_button_loadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_panel_button_loadFileActionPerformed
        gui_state.first_panel_path_protect_compress = file_chooser_dialog();
        first_panel_text_field_path.setText(gui_state.first_panel_path_protect_compress);
    }//GEN-LAST:event_first_panel_button_loadFileActionPerformed

    private void first_panel_protect_checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_panel_protect_checkBoxActionPerformed
        gui_state.first_panel_protect = first_panel_protect_checkBox.isSelected();
    }//GEN-LAST:event_first_panel_protect_checkBoxActionPerformed

    private void first_panel_button_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_panel_button_acceptActionPerformed
        gui_state.first_panel_date_time_model = (SpinnerDateModel) first_panel_date_time.getModel();
        ResultType infoToShow = gui_state.first_panel_action();
        if(infoToShow.isError())
            error_operation_Dialog(infoToShow);
        else
            succesful_operationDialog(infoToShow);
    }//GEN-LAST:event_first_panel_button_acceptActionPerformed

    private void first_panel_module_size_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_panel_module_size_comboBoxActionPerformed
         switch (first_panel_module_size_comboBox.getSelectedIndex()) {
            case 0:
                gui_state.first_panel_module_size_first = 32;
                break;
            case 1:
                gui_state.first_panel_module_size_first = 128;
                break;
            case 2:
                gui_state.first_panel_module_size_first = 1024;
                break;
            case 3:
                gui_state.first_panel_module_size_first = 4096;
                break;
            case 4:
                gui_state.first_panel_module_size_first = 16384;
                break;
        }
    }//GEN-LAST:event_first_panel_module_size_comboBoxActionPerformed

    private void first_panel_insert_error_checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_panel_insert_error_checkBoxActionPerformed
        gui_state.first_panel_insertError = first_panel_insert_error_checkBox.isSelected();
    }//GEN-LAST:event_first_panel_insert_error_checkBoxActionPerformed

    private void first_panel_compress_checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_panel_compress_checkBoxActionPerformed
        gui_state.first_panel_compress = first_panel_compress_checkBox.isSelected();
    }//GEN-LAST:event_first_panel_compress_checkBoxActionPerformed

    private void second_panel_file_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_second_panel_file_buttonActionPerformed
        gui_state.second_panel_path_unprotect_uncompress = file_chooser_dialog();
        second_panel_text_field_path.setText(gui_state.second_panel_path_unprotect_uncompress);
    }//GEN-LAST:event_second_panel_file_buttonActionPerformed

    private void second_panel_unprotect_checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_second_panel_unprotect_checkBoxActionPerformed
        gui_state.second_panel_unprotect = second_panel_unprotect_checkBox.isSelected();
    }//GEN-LAST:event_second_panel_unprotect_checkBoxActionPerformed

    private void second_panel_fix_checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_second_panel_fix_checkBoxActionPerformed
        gui_state.second_panel_toCorrect = second_panel_fix_checkBox.isSelected();
    }//GEN-LAST:event_second_panel_fix_checkBoxActionPerformed

    private void second_panel_unzip_checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_second_panel_unzip_checkBoxActionPerformed
        gui_state.second_panel_decompress = second_panel_unzip_checkBox.isSelected();
    }//GEN-LAST:event_second_panel_unzip_checkBoxActionPerformed

    private void second_panel_button_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_second_panel_button_acceptActionPerformed
        ResultType infoToShow = gui_state.second_panel_action();
        if(infoToShow.isError())
            error_operation_Dialog(infoToShow);
        else
            succesful_operationDialog(infoToShow);
    }//GEN-LAST:event_second_panel_button_acceptActionPerformed

    
    public String file_chooser_dialog(){
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getDefaultDirectory());
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            return selectedFile.getAbsolutePath();
        }
        return null;
    }
    
    public void succesful_operationDialog(ResultType result){
        JOptionPane.showMessageDialog(null, result.getMsg() + "\n\n \tTamaño Original = \t"+result.getOriginalSize() + " bytes" + "\n \tTamaño Nuevo = \t" + result.getNewSize() + " bytes", "Resultado de la Operación", JOptionPane.INFORMATION_MESSAGE);
    }

    //Error in operation
    public void error_operation_Dialog(ResultType result){
        JOptionPane.showMessageDialog(null, result.getMsg(), "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton first_panel_button_accept;
    private javax.swing.JButton first_panel_button_loadFile;
    private javax.swing.JCheckBox first_panel_compress_checkBox;
    private javax.swing.JSpinner first_panel_date_time;
    private javax.swing.JCheckBox first_panel_insert_error_checkBox;
    private javax.swing.JComboBox<String> first_panel_module_size_comboBox;
    private javax.swing.JCheckBox first_panel_protect_checkBox;
    private javax.swing.JTextField first_panel_text_field_path;
    private javax.swing.JLabel first_panel_title;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton second_panel_button_accept;
    private javax.swing.JButton second_panel_file_button;
    private javax.swing.JCheckBox second_panel_fix_checkBox;
    private javax.swing.JTextField second_panel_text_field_path;
    private javax.swing.JLabel second_panel_title_label;
    private javax.swing.JCheckBox second_panel_unprotect_checkBox;
    private javax.swing.JCheckBox second_panel_unzip_checkBox;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
